### PR TITLE
Chore/fix linting

### PR DESCRIPTION
**Pull request by Connor-Johnson-DCO**
### What changed

- Fixed the linting issues from eslint
- Removed prettier from npm

### Why did it change

- New workflow added that uses linting and causing failure on new PRs
- Prettier is already apart of pre-commit so no point of having it in npm also

### Environment variables or secrets

- [X] No environment variables or secrets were added or changed

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

### CODE REVIEW

**Review by surajkumar — CHANGES_REQUESTED** [review]
I have added your linting fixes to https://github.com/alphagov/di-ipv-cri-otg-hmrc/pull/8

We should close this PR

**Review by scronk1 — COMMENTED** [review]
Happy to change the workflow to only use eslint but could we keep prettier as a command too? I think it's useful to have a whole bag `npm run lint` command. What do you think?

**Comment by surajkumar** [comment]
> Happy to change the workflow to only use eslint but could we keep prettier as a command too? I think it's useful to have a whole bag `npm run lint` command. What do you think?
Prettier won't run on the whole project but only the lambda its defined in.

**Comment by Connor-Johnson-DCO** [comment]
> Happy to change the workflow to only use eslint but could we keep prettier as a command too? I think it's useful to have a whole bag `npm run lint` command. What do you think?

Because we have removed prettier as a dependancy from npm, it is now through pre-commit that prettier can be run via npm scripts. The caveat being you cannot do a `check` files as it only does a `write`, so combining the two would cause prettier to try and fix the files and eslint to only check them. Could create a `lint:fix` script?

Any further discussion continue on: https://github.com/alphagov/di-ipv-cri-otg-hmrc/pull/8

**Pull request closed without merging**
